### PR TITLE
updated link

### PR DESCRIPTION
**Pull request by romanimm**

### CODE REVIEW

**Comment by kripken** [comment]
Thanks!

**Comment by ebraminio** [comment]
Hi @kripken, I am a maintainer on harfbuzz project and like to add emscripten support to harfbuzz upstream, can you have a look at https://github.com/harfbuzz/harfbuzz/pull/743 which tries to add the support? Thanks.

**Comment by kripken** [comment]
@ebraminio sounds great! The PR seems to just edit the CMakeLists.txt file which is part of the build system, I'm not sure what to look at there? Or is it the comments and discussion you want me to look at?

**Comment by ebraminio** [comment]
Yes, this [part](https://github.com/harfbuzz/harfbuzz/pull/743/files#diff-af3b638bc2a3e6c650974192a53c7291R533) specially. Like projects hosted on this organization, I wish harfbuzz would have a recommended way to be built with, doing best for the users.

**Pull request merged**
